### ISSUE TITLE
`4 Installers\1 Installers.ps1` - `Google Chrome` URL

### ISSUE THREAD

**Issue by Obegg** [fr33thytweaks/Ultimate-Windows-Optimization-Guide#10]
Instead of:
https://github.com/fr33thytweaks/Ultimate-Windows-Optimization-Guide/blob/11f80fdb98fec74b2e342c2e1825b5556bb790e0/4%20Installers/1%20Installers.ps1#L166
Which downloads a 32bit Google Chrome

Use:
```powershell
Get-FileFromWeb -URL "https://dl.google.com/dl/chrome/install/googlechromestandaloneenterprise64.msi" -File "$env:TEMP\Chrome.msi"
```
Which downloads a 64bit Google Chrome

Also use `/quiet` to silent install

**Comment by fr33thytweaks** [comment]
added thankyou!
