### ISSUE TITLE
`5 Graphics\1 Clean Driver.ps1` - `DDU` URL?

### ISSUE THREAD

**Issue by Obegg** [fr33thytweaks/Ultimate-Windows-Optimization-Guide#12]
In this line:
https://github.com/fr33thytweaks/Ultimate-Windows-Optimization-Guide/blob/11f80fdb98fec74b2e342c2e1825b5556bb790e0/5%20Graphics/1%20Clean%20Driver.ps1#L46
How did you reach this URL? Does this URL always returns the latest DDU?
I have reached a different URL and a different method of returning latest DDU, so please share yours.

Also, it appears on this line:
https://github.com/fr33thytweaks/Ultimate-Windows-Optimization-Guide/blob/11f80fdb98fec74b2e342c2e1825b5556bb790e0/5%20Graphics/1%20Clean%20Driver.ps1#L52
you have to manually update the version, which is inefficient, you'll have to keep it up-to-date manually.

**Comment by fr33thytweaks** [comment]
the url always returns the latest, so i need to manually update the link
