### ISSUE TITLE
`5 Graphics\4 Nvidia Driver.ps1` -`NvCleanInstall` URL?

### ISSUE THREAD

**Issue by Obegg** [fr33thytweaks/Ultimate-Windows-Optimization-Guide#13]
In this line:
https://github.com/fr33thytweaks/Ultimate-Windows-Optimization-Guide/blob/11f80fdb98fec74b2e342c2e1825b5556bb790e0/5%20Graphics/4%20Nvidia%20Driver.ps1#L88
It appears you have found a URL which you can download from, kudos to you, much appreciated, been searching for a way to do so, no luck on my end, but only one problem - how do you keep it up-to-date? Hypothetically, version 1.17 released 1 minute ago, your script doesn't know, so do you think it would be possible to get to solution where it downloads the latest up-to-date version automatically?

Edit1:
It appears this domain is the same as the `Notepad++` line found here:
https://github.com/fr33thytweaks/Ultimate-Windows-Optimization-Guide/blob/11f80fdb98fec74b2e342c2e1825b5556bb790e0/4%20Installers/1%20Installers.ps1#L190
So, does this mean it's not the official URL, it's just a 3rd party website?

**Comment by fr33thytweaks** [comment]
its a 3rd party website
tech power up puts protections in for multiple downloads from same link
very frustrating
