### ISSUE TITLE
`.reg` files (and registry commands) inside `.ps1` files

### ISSUE THREAD

**Issue by Obegg** [fr33thytweaks/Ultimate-Windows-Optimization-Guide#15]
I'm not sure why things like `reg add` exists on this project, here's an example:
https://github.com/fr33thytweaks/Ultimate-Windows-Optimization-Guide/blob/11f80fdb98fec74b2e342c2e1825b5556bb790e0/Allow%20Scripts.cmd#L28

if we are using PowerShell we can use something like:
```powershell
New-ItemProperty -Path 'HKLM:\Software\Foo\Foo\Foo\Foo' -Name 'Bar' -Value 1 -PropertyType DWord -Force
```

All across the project there are many repeated `reg add` and alike, such as creating a `.reg` file with the `Set-Content` command, example:
https://github.com/fr33thytweaks/Ultimate-Windows-Optimization-Guide/blob/11f80fdb98fec74b2e342c2e1825b5556bb790e0/6%20Windows/1%20Start%20Menu%20Taskbar.ps1#L67-L136

It's as if we are combining CMD commands with `.reg` files and with PowerShell comamnds, I find it a bit on the ugly side, while it's just an aesthetic and not actually impactful, I think it's important to at least mention it.

**Comment by fr33thytweaks** [comment]
powershell has lots of issues applying and forcing reg keys
never any issues with pipeline through cmd

reg add
reg delete
or cmd.exe reg add

if you write enough scripts you would understand
there is a method behind the madness

when i started this guide i was just using powershell syntax for regedit
it sux and always bugs out with certain things
