### ISSUE TITLE
allow Microphone privacy setting

### ISSUE THREAD

**Issue by wapposhouse** [fr33thytweaks/Ultimate-Windows-Optimization-Guide#17]
i Have to press/allow ´´PrivacySettings for microphone´´ to speak wtih my headset, but when i press it crashes intantly. i need help pls

**Comment by fr33thytweaks** [comment]
you disabled services

**Comment by wapposhouse** [comment]
wich exact service ?

FR33THY ***@***.***> schrieb am Mi. 22. Mai 2024 um 02:46:
