### ISSUE TITLE
Addition to `PowerPlan` - `Processor idle disable`

### ISSUE THREAD

**Issue by Obegg** [fr33thytweaks/Ultimate-Windows-Optimization-Guide#19]
```powershell
powercfg /attributes SUB_PROCESSOR 5d76a2ca-e8c0-402f-a133-2158492d58ad -ATTRIB_HIDE
powercfg /setacvalueindex scheme_current sub_processor 5d76a2ca-e8c0-402f-a133-2158492d58ad 1
```
Source: https://docs.google.com/document/d/1c2-lUJq74wuYK1WrA_bIvgb89dUN0sj8-hO3vqmrau4/edit

**Comment by fr33thytweaks** [comment]
Hey, I will be addressing these issues when i get a chance.
Sorry I've been quite busy. Thanks for your input!

This optimization is placebo and will just make your cpu run hotter.
I wont be adding this one sorry...

**Comment by fr33thytweaks** [comment]
In theory, this actually will make driver latency maybe a few nanoseconds lower. 
Unfortunately this does not affect throughput latency or milliseconds. 

So I wont brush you off like that, but unfortunately it will make some systems thermal throttle more/no gain to be had so it's not worth it.

**Comment by fr33thytweaks** [comment]
this isnt something you want to do
0% difference in throughput latency and fps
