### ISSUE TITLE
Download and/or clone repo triggers Trojan defender warning...

### ISSUE THREAD

**Issue by Spokkis** [fr33thytweaks/Ultimate-Windows-Optimization-Guide#2]
Any idea of why this happens, and has anyone else recieved the same?
<img width="529" alt="fr33thy" src="https://github.com/fr33thytweaks/Ultimate-Windows-Optimization-Guide/assets/66114737/a18a5bf5-0281-4638-8596-b73013f55c5a">

**Comment by fr33thytweaks** [comment]
Hey Spokkis! 'Start Menu Tasbar.ps1' is flagged, i will fix it ASAP. Thanks for the feedback.

**Comment by Spokkis** [comment]
> Hey Spokkis! 'Start Menu Tasbar.ps1' is flagged, i will fix it ASAP. Thanks for the feedback.

Much appreciated! Love your work btw, been using your windows optimization for a year now on my desktop pc and laptop 🤩

**Comment by fr33thytweaks** [comment]
All sorted, it was flagged by a long binary reg add line.
Instead, it's ported to create reg/import reg and no issues, checked with virus total and defender.

Thanks!
