### ISSUE TITLE
Load hidusbf with secure boot on

### ISSUE THREAD

**Issue by RoyalQX** [fr33thytweaks/Ultimate-Windows-Optimization-Guide#20]
if you look through [this](https://github.com/LordOfMice/hidusbf/issues/132) issue on the hidusbf github there’s two different registry keys that allow it to work with secure boot on.

**Comment by fr33thytweaks** [comment]
HUGE for valorant players that occasionally use controller on w11!
Does it work for 8000mhz drivers? I'll have to test xD

**Comment by fr33thytweaks** [comment]
For when change this script. Too busy with work rn. Thanks alot Royal!

![image](https://github.com/fr33thytweaks/Ultimate-Windows-Optimization-Guide/assets/168888348/77a309c6-f6dc-4ba7-b917-3ba6cd1e140e)

**Comment by RywaZ** [comment]
you need that for use hidusbf with secure boot 

[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\CI\Policy]
"WHQLSettings"=dword:00000001

**Comment by fr33thytweaks** [comment]
updated script, THANKS GUYS!
