### ISSUE TITLE
Windows Activation

### ISSUE THREAD

**Issue by RywaZ** [fr33thytweaks/Ultimate-Windows-Optimization-Guide#21]
![image](https://github.com/fr33thytweaks/Ultimate-Windows-Optimization-Guide/assets/124745850/04b182c7-ce82-4994-a138-7aba3c43291e)
My Windows is activate and i have this i think is due to some service disabled

**Comment by fr33thytweaks** [comment]
why are you running services disabled as a daily?
of course this is going to happen over time.

software protection service is disabled. 
revert back to services default.

**Comment by EcA2AcE** [comment]
My man!What steps have been taken to confirm malware or sketch cannot be injected into your zips and files on GitHub? I have a friend who is concerned that someone with ill intent could inject into your files after you are done with them. I believe it would be beneficial for you to discuss or address such concerns with those who may be concerned.Thank you for all your hard work! I am going to donate some cash your way out of respect for your efforts as soon as I am in a position to do so!Respectfully,KennySent from my iPhoneOn May 28, 2024, at 7:57 PM, FR33THY ***@***.***> wrote:﻿
why are you running services disabled as a daily?
of course this is going to happen over time.
software protection service is disabled.
revert back to services default.

**Comment by fr33thytweaks** [comment]
well my github would have to be hacked for that to happen/password leaked
@EcA2AcE

**Comment by EcA2AcE** [comment]
Makes sense to me, Ill let him know once again he has nothing to worry
about... I get his concern, aloty of sketch out in the world however I will
reassure him again that you are the true Legit!

Thank You!
