### ISSUE TITLE
Allow option to use custom Nvidia driver version when using "4 Nvidia Driver.ps1"

### ISSUE THREAD

**Issue by jvmsangkal** [fr33thytweaks/Ultimate-Windows-Optimization-Guide#27]
This would be a good option when the latest Nvidia driver has an issue and users can choose which driver to install. Or maybe a separate script to downgrade version

**Comment by fr33thytweaks** [comment]
you could just use nvclean install for that?
its an option in the script 

thanks for the suggestion though
