### ISSUE TITLE
i have a asus rog strix g15 g513rc hn062w

### ISSUE THREAD

**Issue by AayushV12** [fr33thytweaks/Ultimate-Windows-Optimization-Guide#28]
i mostly play valorant,i need to know i have amd ryzen 7 6800h .whether should i disable modern standby and c states with the aim of getting a competitive advantage in valorant on my laptop connected to power at all times.

**Comment by fr33thytweaks** [comment]
on amd architecture there is no need to disable cstates, its a completely different boost algorithm to intel. your cpu may boost a little worse if you do, typically id only disable it on AMD cpus for 8k polling rate stability.
