### ISSUE TITLE
autounattend script breaks if not stored on C:

### ISSUE THREAD

**Issue by nicowinnerballs** [fr33thytweaks/Ultimate-Windows-Optimization-Guide#3]
![image](https://github.com/fr33thytweaks/Ultimate-Windows-Optimization-Guide/assets/86171818/d65caefe-0aed-4a7a-98d0-69f162f05629)
script stored on F drive - autounattend.xml is not created or moved to the USB after inputting drive letter name

![image](https://github.com/fr33thytweaks/Ultimate-Windows-Optimization-Guide/assets/86171818/982486c4-8747-4916-b90a-f3da7f8d2de1)
script stored on C drive - autounattend.xml created and moved as expected

plaintext error

Set-Content : Could not find a part of the path 'F:\Windows\Temp\autounattend.xml'.
At F:\opti\2 Refresh\4 Autounattend.ps1:157 char:44
tend.xml" | Set-Content -Encoding utf8 "$env:C:\Windows\Temp\autounat ...
CategoryInfo          : ObjectNotFound: (F:\Windows\Temp\autounattend.xml:String) [Set-Content], DirectoryNotFoundException
FullyQualifiedErrorId : GetContentWriterDirectoryNotFoundError,Microsoft.PowerShell.Commands.SetContentCommand`

**Comment by fr33thytweaks** [comment]
Thanks! I'll get onto this ASAP

**Comment by fr33thytweaks** [comment]
fixed
