### ISSUE TITLE
replace all `$env:C:` with `$env:SystemDrive`

### ISSUE THREAD

**Issue by rjdXpxigYxNT** [fr33thytweaks/Ultimate-Windows-Optimization-Guide#30]
just do a replace all `$env:C:` with `$env:SystemDrive`
probably is the proper method to get the windows drive
maybe fixes https://github.com/fr33thytweaks/Ultimate-Windows-Optimization-Guide/issues/3 (unless that is a different issue and is already fixed)

**Comment by fr33thytweaks** [comment]
im getting onto this, huge headache but needs to be done

**Comment by fr33thytweaks** [comment]
fixed
