### ISSUE TITLE
disable web search box

### ISSUE THREAD

**Issue by rjdXpxigYxNT** [fr33thytweaks/Ultimate-Windows-Optimization-Guide#31]
some registry keys to disable web search that can be added
```
; Disable web search
[HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Search]
"BingSearchEnabled"=dword:00000000

[HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Search]
"CortanaConsent"=dword:00000000
```

**Comment by fr33thytweaks** [comment]
yeah i think those reg keys are no longer needed?
at least on the new build of windows
might be dead reg keys?

![image](https://github.com/fr33thytweaks/Ultimate-Windows-Optimization-Guide/assets/168888348/7af90ca6-3456-4f98-bbf1-6b89d5d5b489)
 
 ; disable web search in start menu 
[HKEY_CURRENT_USER\Software\Policies\Microsoft\Windows\Explorer]
"DisableSearchBoxSuggestions"=dword:00000001
 
 i only need this for w10 and w11 (updated)
 
 
![image](https://github.com/fr33thytweaks/Ultimate-Windows-Optimization-Guide/assets/168888348/f19a6cb5-5678-4334-add1-2f76f6c888be)

![image](https://github.com/fr33thytweaks/Ultimate-Windows-Optimization-Guide/assets/168888348/a2a4a4b3-a6cb-4c70-9d6a-bca6b978741a)

thankyou for the suggestion though
