### ISSUE TITLE
Registry.ps1 worst performance then the previous version

### ISSUE THREAD

**Issue by FacundoMolina04** [fr33thytweaks/Ultimate-Windows-Optimization-Guide#32]
In the previous version of Registry.ps1, it looks smoother and 0.1% better. When I run the new version, the input delay is better, but the performance decreases. I have tested it in several games, and the result is the same.

It feels much more responsive, but having less performance than the previous version is a problem. I hope you see this and can take a look.

Good job with the ultimate windows optimization guide Chris!

PC:
CPU: Ryzen 5 3600
GPU: RX 6600XT
RAM: G.Skill Trident Z Neo 3600MHz CL16
OS: Win10 Pro

**Comment by fr33thytweaks** [comment]
could it be the old registry disabled fullscreen optimizations?
thats really the only difference man im going to be honest

fso has its own script in advanced
ive not seen this impact framerate, although ive been told on weaker systems it did for csgo back in the day?

what games are you playing on that hardware?

**Comment by fr33thytweaks** [comment]
also how are you measuring 0.1% lows, id recommend frame view or capframe x. frameview will work with amd cards.

**Comment by fr33thytweaks** [comment]
yeah look mate, its defiantly something wrong with your rig or your doing something wrong. or everyone would be complaining. 20000 users on github already.
