### ISSUE TITLE
window snapping issue with multiple monitors and 4k+ polling

### ISSUE THREAD

**Issue by RoyalQX** [fr33thytweaks/Ultimate-Windows-Optimization-Guide#34]
When the registry key "DITest" is set to 0 in [HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced] and mouse polling rate is 4k+ dragging windows across monitors becomes very difficult.

https://github.com/fr33thytweaks/Ultimate-Windows-Optimization-Guide/assets/66643139/15884bb3-94dc-4732-82ea-e92231b05f9c

**Comment by fr33thytweaks** [comment]
enable all these?

![image](https://github.com/fr33thytweaks/Ultimate-Windows-Optimization-Guide/assets/168888348/c6af45b8-a947-4924-addd-35aa3847c70c)

**Comment by fr33thytweaks** [comment]
its probably one of them

**Comment by RoyalQX** [comment]
yeah its the last one i just opened this to make it easy for others to find the fix
