### ISSUE TITLE
Advanced cleanup

### ISSUE THREAD

**Issue by yeah-Buddyy** [fr33thytweaks/Ultimate-Windows-Optimization-Guide#35]
Hi,

I have modified your windows cleanup script, if you like it you could add it to your repository.

https://github.com/yeah-Buddyy/Windows-Cleaner/

**Comment by fr33thytweaks** [comment]
Hey man, cool script.
This is just overly excessive for a simple disk cleanup in my guide, im afraid ill have  to pass.
Thankyou for the suggestion though!
