### ISSUE TITLE
Black screen after safe mode 

### ISSUE THREAD

**Issue by 5m1rk** [fr33thytweaks/Ultimate-Windows-Optimization-Guide#36]
I'm halfway through the optimisation guide, where the script boots into safe mode, and it has given me a black screen. Booting into bios works, but can't get into windows.

**Comment by fr33thytweaks** [comment]
is this on w11, i have had issues with safe mode on some hardware with safe mode.
it's not a script thing, its a windows bug. 

try and fail boot 3 times then do a restore point in the blue recovery screen.

**Comment by 5m1rk** [comment]
Should I move the troubleshooting off discord and on here?

It might be a case of reinstalling windows and going from there. Maybe skipping the safe mode bit?

**Comment by JeromeGodbout777** [comment]
I have the same problem. I'm on W11 and when I launch in safe mode my PC won't start. The loading menu freezes and I can't even get to the blue recovery screen. Do you have a solution?

**Comment by fr33thytweaks** [comment]
this is just w11 being buggy, i have had the same issue
