### ISSUE TITLE
Services Off Problem

### ISSUE THREAD

**Issue by RywaZ** [fr33thytweaks/Ultimate-Windows-Optimization-Guide#37]
Services Off make windows explorer crash , blacksreen (Im on Win11)
![image](https://github.com/user-attachments/assets/b107149c-40ab-4f58-a0f9-1a7bb47dd1c5)

**Comment by fr33thytweaks** [comment]
its working fine on everyone else's end, is this a fresh install?

**Comment by fr33thytweaks** [comment]
is your language in English for windows?

**Comment by RywaZ** [comment]
> is your language in English for windows?

No my Windows are in French i never have problem with services before

**Comment by fr33thytweaks** [comment]
thats your issue man, some of these scripts will bug out if the windows language isnt in english
