### ISSUE TITLE
How to get the ability to turn sleep and lock options back in control panel?

### ISSUE THREAD

**Issue by samio5** [fr33thytweaks/Ultimate-Windows-Optimization-Guide#40]
Hello fr33thytweaks & contributors,

I have been following the ultimate windows optimization guide and I am grateful for the hard work you guys have put together. 

My question is how can I bring back the lock and sleep options inside the power button in the start menu? I have checked 12 Registry.ps1 script for them and I have found the registry keys as shown in the images provided, but I do not know what the default values are. I am not sure if I am looking at the right place to re-enable the options so I hope to get some help with this issue.

Once again, thank you.

![Screenshot 2024-08-07 203431](https://github.com/user-attachments/assets/a04e49af-fbe7-4e7f-9976-5002a036b131)

![Screenshot 2024-08-07 203808](https://github.com/user-attachments/assets/c700c2fd-5214-4dae-9ecd-8a0547d62867)

![Screenshot 2024-08-07 203820](https://github.com/user-attachments/assets/9f357d14-3e57-4b73-842a-023a36d43464)

![Screenshot 2024-08-07 203947](https://github.com/user-attachments/assets/e33f5d1d-c558-4694-88db-275e500fa0b6)

**Comment by zoicware** [comment]
set show sleep option to 1 
result:
![image](https://github.com/user-attachments/assets/e6d0269d-7a56-4ca4-a7b4-2c0093d10182)

**Comment by samio5** [comment]
Ok, thanks.
