### ISSUE TITLE
Windows 10/11 Installation Error

### ISSUE THREAD

**Issue by mahifps** [fr33thytweaks/Ultimate-Windows-Optimization-Guide#41]
Windows installation throws the following error when no account name is given/left blank in autounattend.ps1. This will halt the installation process. To proceed with the installation, we have reconfigure the autounattend file with an account name. Could you add a default account name when the user provides no name?
![SKY20240801_030015255v11f](https://github.com/user-attachments/assets/f0e23257-81c5-439c-bf15-19395b8b5b00)

**Comment by gameshler** [comment]
by default windows asks you to insert a name and I think its essential, just put your preferred username and get on with the installation

**Comment by fr33thytweaks** [comment]
great find, tysm

**Comment by fr33thytweaks** [comment]
thanks guys

# force user to not leave it blank
do {
$username = Read-Host -Prompt "Enter Account Name"
} while ([string]::IsNullOrWhiteSpace($username))
(Get-Content $path) -replace "@",$username | out-file $path
