### ISSUE TITLE
DDU not opening in safe mode!!!

### ISSUE THREAD

**Issue by Iceman828** [fr33thytweaks/Ultimate-Windows-Optimization-Guide#43]
im just wondering why everytime i try and clean my drivers using DDU through the links it boots into safe mode ok but when in safe mode im not able to open DDU in safe mode. before booting into safe mode and clicking onto the clean drivers link it comes up with some error im not sure why or what it mean but some help would be great to resolve this cheers and thank you.

**Comment by fr33thytweaks** [comment]
not getting any error on my end
i dont really understand your issue can you explain it a little better

what do you mean "when in safe mode im not able to open DDU in safe mode"

**Comment by Iceman828** [comment]
Sorry for the late response but when I’ve gone into safe mode through the latest optimisation pack it cannot find the short cut and comes up with an error when I hop onto my computer I’ll screenshot what I mean and also I’m following the tutorial step by step I’m not sure why I’m getting the error


________________________________
