### ISSUE TITLE
Extras to add in Reg.ps1

### ISSUE THREAD

**Issue by NLPalm** [fr33thytweaks/Ultimate-Windows-Optimization-Guide#44]
Added 3 new lines that could be added to the Reg Script:
1. Turn off Windows Error Reporting.

![image](https://github.com/user-attachments/assets/8915bf72-c348-4d85-98bb-54b8ab60c366)

2.  Disable Telemetry.

![image](https://github.com/user-attachments/assets/29c9650f-9d93-47a3-9ac1-561c5cdc59ed)

3. Remove Bell Icon from Taskbar.

![image](https://github.com/user-attachments/assets/6ebdf239-ad77-47d1-940f-db5f0e81bc33)

Windows Registry Editor Version 5.00

;Error reporting disabled

[HKEY_LOCAL_MACHINE\Software\Policies\Microsoft\PCHealth\ErrorReporting]
"DoReport"=dword:00000000

[HKEY_LOCAL_MACHINE\Software\Policies\Microsoft\Windows\Windows Error Reporting]
"Disabled"=dword:00000001

;Turn off Telemetry

[HKEY_LOCAL_MACHINE\Software\Policies\Microsoft\Windows\DataCollection]
"AllowTelemetry"=dword:00000000

;Removes Bell icon on Taskbar

[HKEY_CURRENT_USER\Software\Policies\Microsoft\Windows\Explorer]
"DisableNotificationCenter"=dword:00000001

**Comment by fr33thytweaks** [comment]
thanks mate, done

not disabling notification center as it bricks calendar flyout in w11
