### ISSUE TITLE
Services enabled instead of disabled?

### ISSUE THREAD

**Issue by harmine21** [fr33thytweaks/Ultimate-Windows-Optimization-Guide#45]
There are 23 instances of services being set to automatic start and 18 instances of services being set to manual start while the rest of the services are just set to disabled. This is seen on [Service Disabler](https://github.com/fr33thytweaks/Ultimate-Windows-Optimization-Guide/blob/main/8%20Advanced/9%20Services.ps1) on the "Services: Off" option.

The "Start" key can have these values:
0 - Boot
1 - System
2 - Automatic
3 - Manual
4 - Disabled

Is this behavior intentional? If so, could you clarify the reasoning behind it?

Thank you for your work on this—I'm looking forward to contributing soon.

**Comment by fr33thytweaks** [comment]
yes so the os doenst brick and you can use basic functions like game launchers, games and webrowsers
it was a nightmare to get right
