### ISSUE TITLE
Mouse stuttering/freezing for a sec randomly on Win10

### ISSUE THREAD

**Issue by CovidThe19th** [fr33thytweaks/Ultimate-Windows-Optimization-Guide#47]
Ever since following along the video step by step for Windows 10, I've found that my mouse keeps randomly stuttering/freezing for a moment and this has only ever happened since following the optimizations. I can't seem to find the cause or a solution other than reverting to my prior restore point which I'd prefer not do if possible. 

Do you happen to know if there is any particular step that could've caused this or solution? Any help would be greatly appreiated!

**Comment by fr33thytweaks** [comment]
hey mate, it would be a hardware/stability issue for sure.
the optimization pack would just making anything potentially unstable worse.

id start with the stability stuff as part of the guide, stress test components etc.
