### ISSUE TITLE
About Services

### ISSUE THREAD

**Issue by qidanei624** [fr33thytweaks/Ultimate-Windows-Optimization-Guide#5]
There is an issue with the service, the input method is not displaying, the win settings interface cannot be accessed, and the switch of the eset antivirus software is malfunctioning,
Clash for Windows proxy software is no longer available

**Comment by fr33thytweaks** [comment]
This is by design, its the bare minimal services that windows will run with.
It's not something you should daily.

read the prompt
![1](https://github.com/fr33thytweaks/Ultimate-Windows-Optimization-Guide/assets/168888348/329cf8cf-0b75-49dd-9b02-ed7f5a2df9d8)
