### ISSUE TITLE
Cant run "allow scripts"

### ISSUE THREAD

**Issue by Johnnysnds** [fr33thytweaks/Ultimate-Windows-Optimization-Guide#6]
i tried opening the allow script file with "run as admin"but it doesnt work on my end .A window appears for half a sex and then its gone,i run scripts in the pas so its weird for me ,any fix for my awfully described problem?XD

**Comment by fr33thytweaks** [comment]
Could i get some more info on your windows setup.

Windows version?
Is UAC disabled? 
Using the administrator account?
Any group policies applied on the system?
Have you tried a fresh install/factory reset?

Thanks in advance

**Comment by Johnnysnds** [comment]
-windows 11 pro 
-yes
-yes
-im not sure what that is to be honest or how can i check it
-ill test it soon on a new install i just need to get my ssd 
 (One thing i suspect is the past tweaks ive done smh interfere with cmd).Also havent seen your whole video yet,should the files i downloaded be on the main drive that has windows on it?
 Thank you for the quick reply and thank you for your time.

**Comment by fr33thytweaks** [comment]
i think the issue is you are on the administrator account and uac is disabled
the script is trying to run as administrator again which gets canceled out and wont run

i will test on my end and modify the script when i get time, tysm

**Comment by Johnnysnds** [comment]
i tested with my friends pc,and "allow tweaks"worked perfectly.i've done smth with my previous tweaks so it doesnt work on my end, but if you could troubleshoot the problem you stated i would appreciated,ty for your time

**Comment by Johnnysnds** [comment]
so i tried a new install but i did some debloating with chris titus software and i cant use your tweaks again :
![itus](https://github.com/fr33thytweaks/Ultimate-Windows-Optimization-Guide/assets/170183714/37b9d457-ac41-42ee-a377-29a7c20cbc7a)
these were my settings

**Comment by fr33thytweaks** [comment]
are you actually using the administrator account?
like your user name is administrator?

**Comment by fr33thytweaks** [comment]
look man no one else is having issues so its probably something you are doing with titus script
