### ISSUE TITLE
No tray icon , clock, volume on right side of the taskbar.

### ISSUE THREAD

**Issue by nogigi** [fr33thytweaks/Ultimate-Windows-Optimization-Guide#7]
Hi, 
By runing Advanced/Services.ps1 on Windows 11 PRO 23h2. 
There is no right side of the taskbar (volume , icon tray , internet icon , clock).
![image](https://github.com/fr33thytweaks/Ultimate-Windows-Optimization-Guide/assets/13176489/7af23fd8-4432-4023-9482-028d42c02db7)
Probably a needed service to run this part of the taskbar have been disabled.
Does anyone know wich services is in cause ?

I have roll back to a previous restore point without issue.

**Comment by efeaslansoyler** [comment]
also problem with file explorer in the latest windows 11 version (cant open folders)

**Comment by Fragil1ty** [comment]
> Hi, By runing Advanced/Services.ps1 on Windows 11 PRO 23h2. There is no right side of the taskbar (volume , icon tray , internet icon , clock). ![image](https://private-user-images.githubusercontent.com/13176489/331813710-7af23fd8-4432-4023-9482-028d42c02db7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYwODE4NjksIm5iZiI6MTcxNjA4MTU2OSwicGF0aCI6Ii8xMzE3NjQ4OS8zMzE4MTM3MTAtN2FmMjNmZDgtNDQzMi00MDIzLTk0ODItMDI4ZDQyYzAyZGI3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE5VDAxMTkyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI4YjJhZjZjYzZhYTE5MmQxZGFmZDgzM2E0OTY2ZWE1NDNlY2Y0MDkxYzNkMDBlMGEwNDU0MjkzM2QyODFiMGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rlme7ZfnLruA1YJ1G_a0PJ2iy1NSxpnDg3pM_CiFQMc) Probably a needed service to run this part of the taskbar have been disabled. Does anyone know wich services is in cause ?
> 
> I have roll back to a previous restore point without issue.

You will have to revert the services.ps1 script, there is a revert option (option 2), using the services script is created for minimal use and not for a daily operating system. Think in terms of benchmarking and things of that nature.
