### ISSUE TITLE
`4 Installers\1 Installers.ps1` - `Battle.net` silent install arguments

### ISSUE THREAD

**Issue by Obegg** [fr33thytweaks/Ultimate-Windows-Optimization-Guide#9]
Instead of:
https://github.com/fr33thytweaks/Ultimate-Windows-Optimization-Guide/blob/11f80fdb98fec74b2e342c2e1825b5556bb790e0/4%20Installers/1%20Installers.ps1#L102

Use:
```powershell
Start-Process "$env:TEMP\Battle.net.exe" -ArgumentList '--lang=enUS --installpath="C:\Program Files (x86)\Battle.net"'
```

**Comment by fr33thytweaks** [comment]
love it, will make changes as soon as i get some time on my hands! tysm

**Comment by fr33thytweaks** [comment]
added thankyou!
